### ISSUE TITLE
Can't find "covid.rda" for highlight_geom() line highlight demo

### ISSUE THREAD

**Issue by kirstinhuiber-ac** [ericmshearer/OCepi#1]
Hello!  Do you still have a data set that can show a trend for the "Line highlight" in the "expanding ggplot2" vignette?  I don't see the "covid" data set in the Data folder.

  ggplot(data = covid, aes(x = date, y = rate_ma_7, group = area)) +
    geom_line(linewidth = 1.2) +
    theme_apollo(legend = "Hide") +
    apollo_label(data = end_points(covid, date = date), aes(label = area), hjust = -0.05) +
    highlight_geom(area == "Orange", pal = cdcd_color("orange")) +
    scale_x_date(date_labels = "%m/%Y", date_breaks = "1 month", expand = expansion(add = c(0,15))) +
    scale_y_continuous(expand = c(0,0), limits = c(0,155)) +
    labs(
      x = "Episode Date",
      y = "Crude Rate per 100k",
      color = "County"
    )

**Comment by ericmshearer** [comment]
Hi Kristin,
Here's the code chunk that preps the data for that example:

```
library(OCepi)
library(dplyr)

covid <- read.csv("https://data.chhs.ca.gov/dataset/f333528b-4d38-4814-bebb-12db1f10f535/resource/046cdd2b-31e5-4d34-9ed3-b48cdbc4be7a/download/covid19cases_test.csv", na.strings = "", stringsAsFactors = FALSE) |>
  filter(area %in% c("Orange","Los Angeles","San Diego"))

covid <- covid |>
  group_by(area) |>
  mutate(
    date = as.Date(date, "%Y-%m-%d"),
    rate = rate_per_100k(cases, population, digits = 1),
    rate_ma_7 = round(zoo::rollmean(rate, k = 7, align = "right", na.pad = FALSE, fill = 0), digits = 2)
  ) |>
  ungroup() |>
  filter(date <= "2020-12-23", date > "2020-08-01")
```

**Comment by kirstinhuiber-ac** [comment]
Now I’m embarrassed.  Thank you, Eric!




Kirstin Huiber (she/her)
Epidemiologist, Community Assessment, Planning, and Evaluation
Public Health Department
Alameda County Health

1100 San Leandro Boulevard, Suite 400
San Leandro, CA 94577
TEL (510) 268-4150

Health.AlamedaCountyCA.gov/ACPHD<https://health.alamedacountyca.gov/ACPHD>

***@***.***

**Comment by ericmshearer** [comment]
No worries, it's good feedback for me to be more explicit in examples. I appreciate you reaching out.

**Comment by kirstinhuiber-ac** [comment]
[like]  Huiber, Kirstin, Public Health... reacted to your message:
________________________________
